insert into Store (phone, country, city, adressline) values ('151-243-4052', 'Kazakhstan', 'Shashūbay', '212 Caliangt Parkway');
insert into Store (phone, country, city, adressline) values ('136-891-0258', 'Portugal', 'Miratejo', '44 Scofield Junction');
insert into Store (phone, country, city, adressline) values ('612-179-3311', 'China', 'Shangzhang', '4073 Westport Road');
insert into Store (phone, country, city, adressline) values ('593-684-7836', 'Luxembourg', 'Müllendorf', '9551 Parkside Terrace');
insert into Store (phone, country, city, adressline) values ('370-366-4490', 'Dominican Republic', 'Bella Vista', '177 Sachtjen Terrace');

insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (4, 'Valentino', 'B', 'Bonny', 'vbonny0@creativecommons.org', 'Operator', null);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (5, 'Mallory', 'C', 'Wilhelmy', 'mwilhelmy1@marketwatch.com', 'Teacher', null);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (5, 'Cynthy', 'B', 'Halwill', 'chalwill2@hibu.com', 'Administrative Assistant IV', 2);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (3, 'Chrisy', 'A', 'Josovich', 'cjosovich3@nifty.com', 'Mechanical Systems Engineer', 2);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (4, 'Maible', 'B', 'Rushbrooke', 'mrushbrooke4@newsvine.com', 'Software Engineer III', 2);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (2, 'Dennie', 'K', 'MacConneely', 'dmacconneely5@wp.com', 'Help Desk Operator', 3);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (2, 'Sunshine', 'A', 'Loncaster', 'sloncaster6@qq.com', 'Paralegal', 3);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (4, 'Kristien', 'J', 'Bradford', 'kbradford7@people.com.cn', 'Analog Circuit Design manager', 3);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (5, 'Rebecka', 'C', 'Baccup', 'rbaccup8@example.com', 'Legal Assistant', 3);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (2, 'Taddeo', 'C', 'McCallum', 'tmccallum9@alibaba.com', 'Recruiter', 3);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (4, 'Arlie', 'A', 'Flexman', 'aflexmana@lycos.com', 'Safety Technician II', 3);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (3, 'Margaretta', 'A', 'Crossingham', 'mcrossinghamb@reddit.com', 'Speech Pathologist', 5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (3, 'Candy', 'J', 'Petworth', 'cpetworthc@pbs.org', 'Account Executive',5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (3, 'Kesley', 'B', 'Fidock', 'kfidockd@purevolume.com', 'Nuclear Power Engineer', 5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (1, 'Romola', 'K', 'Brigg', 'rbrigge@github.com', 'Senior Editor', 5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (5, 'Allyn', 'J', 'Hearon', 'ahearonf@sohu.com', 'Software Test Engineer II', 5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (1, 'Minta', 'B', 'Greensides', 'mgreensidesg@nasa.gov', 'Nuclear Power Engineer', 5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (2, 'Lauren', 'J', 'Damrel', 'ldamrelh@blog.com', 'Physical Therapy Assistant', 5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (5, 'Richie', 'B', 'Groomebridge', 'rgroomebridgei@exblog.jp', 'Physical Therapy Assistant', 5);
insert into Employee (employee_storeid, firstname, middleinitial, lastname, email, jobtitle, reports_to) values (4, 'Ansel', 'J', 'Davion', 'adavionj@discuz.net', 'Nurse', 5);

insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (1, 'Olwen', 'L', 'Lartice', 40.74, '438-828-5608', 1035);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (2, 'Alexina', 'A', 'Willment', 4730.6, '404-365-9985', 1046);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (11, 'Timotheus', 'J', 'McSkin', 227.43, '291-810-6474', 1096);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (17, 'Erda', 'J', 'Hartshorn', 886.72, '961-857-2452', 1040);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (1, 'Shelly', 'A', 'Bowld', 684.82, '307-480-9746', 1028);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (8, 'Albertine', 'H', 'Goodere', 424.02, '957-911-9713', 1067);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (1, 'Daloris', 'G', 'Lackham', 218.65, '807-905-7614', 1093);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (1, 'Warren', 'A', 'Newlands', 775.32, '815-787-7770', 1097);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (8, 'Melly', 'K', 'Fordyce', 900.12, '819-847-3462', 1065);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (1, 'Nevins', 'G', 'Winspear', 957.89, '371-267-0526', 1056);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (6, 'Weylin', 'F', 'Jagiello', 387.05, '172-492-5154', 1053);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (18, 'Anthia', 'H', 'Edgeler', 185.54, '302-277-1335', 1081);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (16, 'Cris', 'J', 'Wiszniewski', 938.03, '214-153-2462', 1081);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (6, 'Lamont', 'H', 'Cobbing', 928.96, '653-879-3520', 1029);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (14, 'Son', 'A', 'Frankis', 84.68, '258-926-7210', 1091);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (12, 'Blair', 'A', 'Galtone', 743.44, '338-502-3721', 1037);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (6, 'Gareth', 'Q', 'Lombard', 468.77, '545-456-0174', 1018);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (14, 'Carol', 'J', 'Benedyktowicz', 306.91, '272-299-4473', 1081);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (11, 'Judye', 'Q', 'Brinson', 247.38, '431-491-5276', 1046);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (7, 'Lindy', 'F', 'Trewhela', 575.7, '910-251-5377', 1084);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (9, 'Standford', 'G', 'Richardes', 46.18, '756-547-4219', 1041);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (13, 'Diane-marie', 'F', 'St Ledger', 76.39, '141-196-9928', 1000);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (3, 'Conrado', 'A', 'Arne', 63.79, '587-500-6983', 1063);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (11, 'Lenci', 'F', 'Stiggles', 71.35, '928-660-6918', 1033);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (8, 'Mahmud', 'F', 'Kellet', 672.83, '952-930-0195', 1075);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (7, 'Omero', 'G', 'Wind', 29.16, '109-579-4681', 1032);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (7, 'Mikkel', 'K', 'Jentges', 123.3, '400-729-1918', 1099);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (17, 'Alisha', 'L', 'Chittock', 21.44, '746-267-7994', 1060);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (18, 'Ingmar', 'F', 'Claiton', 56.81, '646-146-8275', 1019);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (12, 'Darrelle', 'H', 'Tipling', 330.44, '440-546-8959', 1083);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (20, 'Matthaeus', 'H', 'Champain', 110.04, '854-141-5125', 1067);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (5, 'Sollie', 'G', 'Lugsdin', 575.24, '795-843-8898', 1055);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (14, 'Syman', 'J', 'Leversha', 226.56, '683-195-2755', 1049);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (13, 'Edd', 'A', 'MacParlan', 4.69, '841-698-3629', 1081);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (18, 'Jaynell', 'F', 'Melling', 6233.08, '942-999-7252', 1006);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (17, 'Armin', 'L', 'Ruddell', 25.48, '437-292-0143', 1089);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (9, 'Katharine', 'Q', 'Bearcock', 3567.99, '848-790-2882', 1061);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (3, 'Hal', 'H', 'Erdes', 5254.38, '347-597-3310', 1092);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (19, 'Tybi', 'K', 'Dunderdale', 1562.13, '632-148-7627', 1058);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (6, 'Howard', 'L', 'Papaccio', 1118.48, '622-281-7515', 1029);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (17, 'Adelle', 'Q', 'Scrafton', 8863.85, '629-341-4693', 1076);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (18, 'Clotilda', 'Q', 'Teodori', 8276.77, '181-388-2616', 1086);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (6, 'Mendie', 'G', 'Eagling', 5983.54, '527-712-1243', 1045);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (12, 'Reggis', 'A', 'Dennehy', 8408.33, '886-593-1745', 1016);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (7, 'Vi', 'Q', 'Dossettor', 3353.76, '605-908-4919', 1036);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (16, 'Raimundo', 'F', 'Gayton', 3034.85, '222-153-2391', 1087);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (10, 'Sabina', 'L', 'Spellacy', 59.96, '632-124-1582', 1018);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (1, 'Jonathan', 'Q', 'Sollas', 7973.68, '913-840-0697', 1034);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (10, 'Janifer', 'H', 'Dunstall', 14.16, '966-430-5692', 1026);
insert into Customer (customer_employeeid, firstname, middleinitial, lastname, creditlimit, phone, postalcode) values (1, 'Les', 'K', 'Oakly', 49.19, '179-992-4631', 1091);

insert into Payment (payment_customerid, paymentdate, amount) values (1, '5/19/2021', 521.2);
insert into Payment (payment_customerid, paymentdate, amount) values (1, '4/28/2021', 547.03);
insert into Payment (payment_customerid, paymentdate, amount) values (1, '8/19/2020', 306.53);
insert into Payment (payment_customerid, paymentdate, amount) values (2, '2/20/2021', 937.51);
insert into Payment (payment_customerid, paymentdate, amount) values (2, '10/11/2020', 593.21);
insert into Payment (payment_customerid, paymentdate, amount) values (2, '1/3/2021', 616.4);
insert into Payment (payment_customerid, paymentdate, amount) values (7, '8/26/2020', 573.42);
insert into Payment (payment_customerid, paymentdate, amount) values (8, '9/24/2020', 956.56);
insert into Payment (payment_customerid, paymentdate, amount) values (9, '10/22/2020', 524.99);
insert into Payment (payment_customerid, paymentdate, amount) values (10, '5/20/2021', 381.69);
insert into Payment (payment_customerid, paymentdate, amount) values (11, '10/23/2020', 159.18);
insert into Payment (payment_customerid, paymentdate, amount) values (12, '12/20/2020', 86.19);
insert into Payment (payment_customerid, paymentdate, amount) values (13, '11/24/2020', 342.84);
insert into Payment (payment_customerid, paymentdate, amount) values (14, '6/12/2020', 604.12);
insert into Payment (payment_customerid, paymentdate, amount) values (15, '10/5/2020', 832.89);
insert into Payment (payment_customerid, paymentdate, amount) values (16, '5/22/2021', 74.07);
insert into Payment (payment_customerid, paymentdate, amount) values (17, '12/18/2020', 979.41);
insert into Payment (payment_customerid, paymentdate, amount) values (18, '11/14/2020', 198.54);
insert into Payment (payment_customerid, paymentdate, amount) values (19, '1/9/2021', 79.05);
insert into Payment (payment_customerid, paymentdate, amount) values (20, '5/5/2021', 339.55);
insert into Payment (payment_customerid, paymentdate, amount) values (21, '1/29/2021', 866.07);
insert into Payment (payment_customerid, paymentdate, amount) values (22, '11/29/2020', 875.41);
insert into Payment (payment_customerid, paymentdate, amount) values (23, '10/21/2020', 293.47);
insert into Payment (payment_customerid, paymentdate, amount) values (24, '3/16/2021', 250.1);
insert into Payment (payment_customerid, paymentdate, amount) values (25, '9/3/2020', 871.42);
insert into Payment (payment_customerid, paymentdate, amount) values (26, '4/15/2021', 746.93);
insert into Payment (payment_customerid, paymentdate, amount) values (27, '4/6/2021', 141.55);
insert into Payment (payment_customerid, paymentdate, amount) values (28, '2/1/2021', 241.56);
insert into Payment (payment_customerid, paymentdate, amount) values (29, '8/12/2020', 65.28);
insert into Payment (payment_customerid, paymentdate, amount) values (30, '8/20/2020', 504.01);
insert into Payment (payment_customerid, paymentdate, amount) values (31, '4/25/2021', 460.66);
insert into Payment (payment_customerid, paymentdate, amount) values (32, '5/25/2021', 704.95);
insert into Payment (payment_customerid, paymentdate, amount) values (33, '11/8/2020', 894.56);
insert into Payment (payment_customerid, paymentdate, amount) values (34, '11/1/2020', 738.17);
insert into Payment (payment_customerid, paymentdate, amount) values (35, '10/27/2020', 765.39);
insert into Payment (payment_customerid, paymentdate, amount) values (36, '7/2/2020', 10.09);
insert into Payment (payment_customerid, paymentdate, amount) values (37, '11/14/2020', 909.75);
insert into Payment (payment_customerid, paymentdate, amount) values (38, '8/17/2020', 157.54);
insert into Payment (payment_customerid, paymentdate, amount) values (39, '6/7/2021', 755.33);
insert into Payment (payment_customerid, paymentdate, amount) values (40, '1/3/2021', 268.13);
insert into Payment (payment_customerid, paymentdate, amount) values (41, '12/19/2020', 957.0);
insert into Payment (payment_customerid, paymentdate, amount) values (42, '5/14/2021', 758.3);
insert into Payment (payment_customerid, paymentdate, amount) values (43, '3/21/2021', 895.13);
insert into Payment (payment_customerid, paymentdate, amount) values (44, '2/12/2021', 962.49);
insert into Payment (payment_customerid, paymentdate, amount) values (45, '3/13/2021', 858.43);
insert into Payment (payment_customerid, paymentdate, amount) values (46, '5/1/2021', 824.27);
insert into Payment (payment_customerid, paymentdate, amount) values (47, '12/16/2020', 944.6);
insert into Payment (payment_customerid, paymentdate, amount) values (48, '6/13/2020', 938.88);
insert into Payment (payment_customerid, paymentdate, amount) values (49, '8/5/2020', 320.47);
insert into Payment (payment_customerid, paymentdate, amount) values (50, '1/9/2021', 638.94);

insert into Orders (order_customerid, orderdate, status, misccomments) values (1, '2/13/2021', 'completed', 'ac lobortis vel dapibus at diam nam tristique tortor eu');
insert into Orders (order_customerid, orderdate, status, misccomments) values (1, '4/6/2021', 'completed', 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum');
insert into Orders (order_customerid, orderdate, status, misccomments) values (1, '11/21/2020', 'completed', 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget');
insert into Orders (order_customerid, orderdate, status, misccomments) values (2, '8/31/2020', 'failed', 'ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl');
insert into Orders (order_customerid, orderdate, status, misccomments) values (2, '6/12/2020', 'failed', 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam');
insert into Orders (order_customerid, orderdate, status, misccomments) values (2, '11/2/2020', 'failed', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras');
insert into Orders (order_customerid, orderdate, status, misccomments) values (7, '5/29/2021', 'completed', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque');
insert into Orders (order_customerid, orderdate, status, misccomments) values (8, '8/31/2020', 'completed', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi');
insert into Orders (order_customerid, orderdate, status, misccomments) values (9, '5/25/2021', 'completed', 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat');
insert into Orders (order_customerid, orderdate, status, misccomments) values (10, '12/31/2020', 'completed', 'lectus in est risus auctor sed tristique in tempus sit amet sem fusce');
insert into Orders (order_customerid, orderdate, status, misccomments) values (11, '1/11/2021', 'completed', 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut');
insert into Orders (order_customerid, orderdate, status, misccomments) values (12, '6/4/2021', 'completed', 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien');
insert into Orders (order_customerid, orderdate, status, misccomments) values (13, '11/30/2020', 'completed', 'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at');
insert into Orders (order_customerid, orderdate, status, misccomments) values (14, '2/1/2021', 'completed', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet');
insert into Orders (order_customerid, orderdate, status, misccomments) values (15, '1/22/2021', 'completed', 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in');
insert into Orders (order_customerid, orderdate, status, misccomments) values (16, '3/20/2021', 'completed', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet');
insert into Orders (order_customerid, orderdate, status, misccomments) values (17, '6/13/2020', 'other', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus');
insert into Orders (order_customerid, orderdate, status, misccomments) values (18, '11/9/2020', 'completed', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui');
insert into Orders (order_customerid, orderdate, status, misccomments) values (19, '11/11/2020', 'other', 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi');
insert into Orders (order_customerid, orderdate, status, misccomments) values (20, '10/8/2020', 'failed', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat');
insert into Orders (order_customerid, orderdate, status, misccomments) values (21, '11/25/2020', 'other', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque');
insert into Orders (order_customerid, orderdate, status, misccomments) values (22, '1/1/2021', 'other', 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis');
insert into Orders (order_customerid, orderdate, status, misccomments) values (23, '2/17/2021', 'other', 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam');
insert into Orders (order_customerid, orderdate, status, misccomments) values (24, '4/6/2021', 'completed', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque');
insert into Orders (order_customerid, orderdate, status, misccomments) values (25, '3/18/2021', 'completed', 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi');
insert into Orders (order_customerid, orderdate, status, misccomments) values (26, '10/18/2020', 'completed', 'fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into Orders (order_customerid, orderdate, status, misccomments) values (27, '5/3/2021', 'completed', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales');
insert into Orders (order_customerid, orderdate, status, misccomments) values (28, '7/13/2020', 'completed', 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into Orders (order_customerid, orderdate, status, misccomments) values (29, '5/29/2021', 'completed', 'rutrum neque aenean auctor gravida sem praesent id massa id nisl');
insert into Orders (order_customerid, orderdate, status, misccomments) values (30, '5/15/2021', 'completed', 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into Orders (order_customerid, orderdate, status, misccomments) values (31, '5/18/2021', 'completed', 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu');
insert into Orders (order_customerid, orderdate, status, misccomments) values (32, '5/27/2021', 'other', 'rhoncus dui vel sem sed sagittis nam congue risus semper');
insert into Orders (order_customerid, orderdate, status, misccomments) values (33, '12/8/2020', 'failed', 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit');
insert into Orders (order_customerid, orderdate, status, misccomments) values (34, '12/22/2020', 'completed', 'purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor');
insert into Orders (order_customerid, orderdate, status, misccomments) values (35, '1/17/2021', 'completed', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies');
insert into Orders (order_customerid, orderdate, status, misccomments) values (36, '3/8/2021', 'other', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into Orders (order_customerid, orderdate, status, misccomments) values (37, '5/10/2021', 'failed', 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar');
insert into Orders (order_customerid, orderdate, status, misccomments) values (38, '5/8/2021', 'failed', 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla');
insert into Orders (order_customerid, orderdate, status, misccomments) values (39, '3/24/2021', 'completed', 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis');
insert into Orders (order_customerid, orderdate, status, misccomments) values (40, '8/31/2020', 'completed', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into Orders (order_customerid, orderdate, status, misccomments) values (41, '1/26/2021', 'completed', 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit');
insert into Orders (order_customerid, orderdate, status, misccomments) values (42, '10/15/2020', 'completed', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl');
insert into Orders (order_customerid, orderdate, status, misccomments) values (43, '7/17/2020', 'completed', 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut');
insert into Orders (order_customerid, orderdate, status, misccomments) values (44, '7/26/2020', 'completed', 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla');
insert into Orders (order_customerid, orderdate, status, misccomments) values (45, '2/6/2021', 'completed', 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris');
insert into Orders (order_customerid, orderdate, status, misccomments) values (46, '4/20/2021', 'completed', 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget');
insert into Orders (order_customerid, orderdate, status, misccomments) values (47, '7/9/2020', 'completed', 'aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio');
insert into Orders (order_customerid, orderdate, status, misccomments) values (48, '12/21/2020', 'completed', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia');
insert into Orders (order_customerid, orderdate, status, misccomments) values (49, '4/1/2021', 'completed', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque');
insert into Orders (order_customerid, orderdate, status, misccomments) values (50, '10/31/2020', 'completed', 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit');

insert into ProductLine (companyname) values ('Kellogg’s');
insert into ProductLine (companyname) values ('Mondelez');
insert into ProductLine (companyname) values ('Mondelez');
insert into ProductLine (companyname) values ('Mondelez');
insert into ProductLine (companyname) values ('Mars');
insert into ProductLine (companyname) values ('Mondelez');
insert into ProductLine (companyname) values ('Mars');
insert into ProductLine (companyname) values ('Coca-Cola');
insert into ProductLine (companyname) values ('General Mills');
insert into ProductLine (companyname) values ('Coca-Cola');
insert into ProductLine (companyname) values ('Coca-Cola');
insert into ProductLine (companyname) values ('Mars');
insert into ProductLine (companyname) values ('Coca-Cola');
insert into ProductLine (companyname) values ('General Mills');
insert into ProductLine (companyname) values ('PepsiCo');
insert into ProductLine (companyname) values ('Nestle');
insert into ProductLine (companyname) values ('General Mills');
insert into ProductLine (companyname) values ('Coca-Cola');
insert into ProductLine (companyname) values ('Mars');
insert into ProductLine (companyname) values ('PepsiCo');

insert into Product (product_productlineid, productname, description, quantityinstock, price) values (1, 'Fruit', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 96, 13.49);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (12, 'Vegetable', 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 7, 13.3);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (8, 'Sweets', 'donec semper sapien a libero nam dui proin leo odio', 64, 16.24);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (10, 'Vegetable', 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum', 72, 16.66);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (18, 'Sweets', 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 2, 2.32);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (5, 'Vegetable', 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 57, 7.05);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (14, 'other', 'diam erat fermentum justo nec condimentum neque sapien placerat ante', 64, 8.83);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (19, 'Beverage', 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 63, 19.78);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (14, 'other', 'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 86, 17.73);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (1, 'Fruit', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra', 75, 5.43);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (15, 'Sweets', 'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur', 40, 5.34);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (12, 'other', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo', 3, 11.26);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (13, 'Meat', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 89, 16.56);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (20, 'Sweets', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 97, 19.84);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (10, 'other', 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', 33, 12.36);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (8, 'Vegetable', 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 90, 18.72);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (18, 'Meat', 'in hac habitasse platea dictumst maecenas ut massa quis augue luctus', 69, 17.1);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (20, 'Sweets', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', 64, 8.22);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (7, 'Sweets', 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu', 14, 5.42);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (12, 'Vegetable', 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum', 33, 11.95);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (7, 'Vegetable', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus', 29, 13.38);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (4, 'other', 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', 27, 16.45);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (13, 'Sweets', 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', 99, 1.54);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (12, 'Sweets', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 97, 17.57);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (18, 'Vegetable', 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula', 92, 11.99);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (5, 'Vegetable', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', 32, 2.08);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (5, 'Meat', 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 54, 12.05);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (6, 'other', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo', 2, 14.64);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (1, 'Beverage', 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 11, 7.57);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (11, 'Sweets', 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 53, 7.53);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (16, 'Beverage', 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 26, 16.36);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (10, 'Meat', 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', 5, 16.19);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (4, 'other', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 15, 18.88);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (5, 'Beverage', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh', 58, 4.68);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (7, 'Fruit', 'diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed', 96, 12.68);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (6, 'Meat', 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis', 45, 5.38);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (12, 'Beverage', 'donec dapibus duis at velit eu est congue elementum in', 97, 8.43);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (18, 'Beverage', 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', 75, 14.88);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (9, 'Fruit', 'nulla sed accumsan felis ut at dolor quis odio consequat varius', 12, 4.87);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (13, 'Fruit', 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', 54, 3.36);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (18, 'Beverage', 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', 92, 18.47);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (12, 'Beverage', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci', 62, 18.39);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (4, 'Meat', 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', 90, 11.84);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (11, 'Vegetable', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', 84, 7.1);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (2, 'Sweets', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum', 51, 7.63);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (4, 'Beverage', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', 23, 8.35);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (12, 'Beverage', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 61, 15.01);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (13, 'Meat', 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', 7, 7.71);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (5, 'other', 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 93, 11.16);
insert into Product (product_productlineid, productname, description, quantityinstock, price) values (15, 'other', 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', 76, 11.09);

insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 2, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 3, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 4, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 5, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 6, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 7, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 8, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 9, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 10, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 11, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 12, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 13, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 14, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 15, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 16, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 17, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 18, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 19, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 20, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 21, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 22, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 23, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 24, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 25, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 26, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 27, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 28, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 29, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 30, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 31, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 32, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 33, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 34, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 35, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 36, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 37, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 38, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 39, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 40, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 41, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 42, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 43, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 44, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 45, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 46, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 47, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 48, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 49, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 50, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 2, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 3, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 4, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 5, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 6, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 7, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 8, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 9, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 10, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 11, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 12, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 13, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 14, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 15, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 16, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 17, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 18, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 19, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 20, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 21, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 22, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 23, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 24, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 25, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 26, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 27, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 28, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 29, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 30, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 31, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 32, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 33, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 34, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 35, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 36, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 37, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 38, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 39, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 40, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 41, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 42, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 43, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 44, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 45, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 46, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 47, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 48, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 49, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 50, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 2, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 3, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 4, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 5, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 6, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 7, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 8, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 9, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 10, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 11, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 12, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 13, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 14, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 15, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 16, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 17, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 18, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 19, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 20, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 21, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 22, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 23, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 24, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 25, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 26, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 27, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 28, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 29, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 30, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 31, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 32, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 33, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 34, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 35, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 36, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 37, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 38, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 39, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 40, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 41, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 42, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 43, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 44, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 45, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 46, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 47, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 48, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 49, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 50, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 2, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 3, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 4, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 5, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 6, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 7, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 8, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 9, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 10, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 11, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 12, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 13, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 14, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 15, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 16, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 17, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 18, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 19, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 20, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 21, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 22, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 23, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 24, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 25, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 26, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 27, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 28, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 29, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 30, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 31, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 32, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 33, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 34, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 35, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 36, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 37, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 38, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 39, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 40, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 41, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 42, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 43, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 44, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 45, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 46, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 47, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 48, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 49, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 50, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 2, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 3, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 4, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 5, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 6, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 7, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 8, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 9, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 10, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 11, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 12, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 13, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 14, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 15, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 16, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 17, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 18, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 19, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 20, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 21, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 22, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 23, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 24, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 25, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 26, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 27, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 28, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 29, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 30, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 31, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 32, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 33, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 34, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 35, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 36, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 37, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 38, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 39, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 40, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 41, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 42, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 43, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 44, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 45, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 46, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 47, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 48, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 49, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 50, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 2, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 3, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 4, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 5, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 6, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 7, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 8, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 9, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 10, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 11, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 12, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 13, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 14, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 15, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 16, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 17, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 18, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 19, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 20, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 21, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 22, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 23, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 24, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 25, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 26, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 27, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 28, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 29, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 30, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 31, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 32, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 33, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 34, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 35, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 36, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 37, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 38, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 39, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 40, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 41, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 42, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 43, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 44, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 45, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 46, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 47, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 48, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 49, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 50, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 2, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 3, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 4, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 5, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 6, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 7, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 8, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 9, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 10, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 11, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 12, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 13, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 14, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 15, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 16, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 17, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 18, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 19, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 20, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 21, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 22, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 23, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 24, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 25, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 26, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 27, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 28, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 29, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 30, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 31, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 32, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 33, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 34, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 35, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 36, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 37, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 38, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 39, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 40, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 41, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 42, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 43, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 44, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 45, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 46, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 47, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 48, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 49, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 50, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 2, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 3, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 4, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 5, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 6, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 7, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 8, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 9, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 10, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 11, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 12, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 13, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 14, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 15, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 16, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 17, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 18, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 19, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 20, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 21, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 22, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 23, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 24, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 25, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 26, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 27, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 28, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 29, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 30, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 31, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 32, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 33, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 34, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 35, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 36, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 37, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 38, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 39, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 40, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 41, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 42, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 43, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 44, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 45, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 46, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 47, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 48, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 49, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 50, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 2, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 3, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 4, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 5, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 6, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 7, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 8, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 9, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 10, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 11, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 12, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 13, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 14, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 15, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 16, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 17, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 18, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 19, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 20, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 21, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 22, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 23, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 24, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 25, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 26, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 27, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 28, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 29, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 30, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 31, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 32, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 33, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 34, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 35, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 36, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 37, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 38, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 39, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 40, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 41, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 42, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 43, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 44, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 45, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 46, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 47, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 48, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 49, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 50, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 2, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 3, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 4, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 5, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 6, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 7, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 8, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 9, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 10, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (1, 11, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (2, 12, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (3, 13, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (4, 14, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (5, 15, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (6, 16, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (7, 17, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (8, 18, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (9, 19, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (10, 20, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (11, 21, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (12, 22, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (13, 23, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (14, 24, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (15, 25, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (16, 26, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (17, 27, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (18, 28, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (19, 29, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (20, 30, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (21, 31, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (22, 32, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (23, 33, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (24, 34, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (25, 35, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (26, 36, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (27, 37, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (28, 38, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (29, 39, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (30, 40, 8);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (31, 41, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (32, 42, 4);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (33, 43, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (34, 44, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (35, 45, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (36, 46, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (37, 47, 1);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (38, 48, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (39, 49, 10);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (40, 50, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (41, 2, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (42, 3, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (43, 4, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (44, 5, 7);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (45, 6, 3);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (46, 7, 6);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (47, 8, 2);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (48, 9, 9);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (49, 10, 5);
insert into OrderDetails (details_productid, details_orderid, quantityordered) values (50, 11, 8);